from enum import Enum


class Currency(Enum):
    CHAOS = "CHAOS"
    REGRET = "REGRET"
    CHISEL = "CHISEL"
    ALCHEMY = "ALCHEMY"
    GCP = "GCP"
    VAAL = "VAAL"
    SCOURING = "SCOURING"
    DIVINE = "DIVINE"
    FUSING = "FUSING"
    REGAL = "REGAL"
    #HORIZONS = "HORIZONS"
    CHAYULA = "CHAYULA"
    RED_SEXTANT = "RED_SEXTANT"
    YELLOW_SEXTANT = "YELLOW_SEXTANT"
    WHITE_SEXTANT = "WHITE_SEXTANT"
